name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Merged Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test

      - name: Build and Test
        run: npm run build

  docker-build:
    id: image
    name: Build and Publish Artifact
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Record Artifact Information
        run: |
          echo "### Docker Artifact" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Git SHA: \ ${{ github.sha }}\ " >> "$GITHUB_STEP_SUMMARY"
          echo "Digest: \ ${{ steps.image.outputs.digest }}\ " >> "$GITHUB_STEP_SUMMARY"




